[PAGOPA-794] V2 API SOAP
pagopa/pagopa-gpd-payments pull request #32
Opened 2023-03-22 16:38 UTC by alessio-acitelli

#### List of Changes

- alignment of the Partner API SOAP to version 2

#### Motivation and Context

- alignment of the Partner API SOAP to version 2

#### How Has This Been Tested?

- junit and manual test 

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-03-27 09:04 UTC, alessio-acitelli commented
update_code

2023-03-28 07:46 UTC, pasqualespica requested changes
good 👍

2023-03-28 07:46 UTC, pasqualespica commented on src/main/java/it/gov/pagopa/payments/service/PartnerService.java
> +    PaymentOptionModelResponse paymentOption = managePaSendRTV2Request(request);
overload mangaPaSentRT

2023-03-28 08:32 UTC, pasqualespica approved these changes

2023-03-28 08:32 UTC, merged